version: '2'
services:
    scraperscheduler-app:
        image: scraperscheduler
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${simlife.registry.password}@simlife-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${simlife.registry.password}@simlife-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://scraperscheduler-mysql:3306/scraperscheduler?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SIMLIFE_SLEEP=30 # gives time for the Simlife Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=scraperscheduler-elasticsearch:9300
    scraperscheduler-mysql:
        extends:
            file: mysql.yml
            service: scraperscheduler-mysql
    scraperscheduler-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: scraperscheduler-elasticsearch
    simlife-registry:
        extends:
            file: simlife-registry.yml
            service: simlife-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
